// types/elevation.ts
export interface Elevation {
    plot_id: string;
    'Job Code': string;
    plot_number: string;
    housetype: string;
    house_no: string | null;
    street: string | null;
    town: string | null;
    postcode: string | null;
    mpan: string;
    panel: string;
    panelkwp: number;
    mcscode: string;
    orientation: string;
    columns: number;
    rows: number;
    phase: number;
    totalstrings: number;
    string1: string;
    string2: string;
    string3: string;
    string4: string;
    inverter: string;
    trackerstringno: string;
    inverterhybrid: string | null;
    typetestno: string;
    ratedoutputpower: number | null;
    battery: string;
    mountingkit: string;
    tiletype: string;
    roofincline: number;
    variationfromsouth: string;
    kwhperkwp: number | null;
    inaboveroof: number | null;
    overshadingfactor: number | null;
    nopanels: number;
    arraym2: number | null;
    kwp: number;
    kwh: number | null;
    co2equivalent: number | null;
    netkwp: number;
    metermake: string | null;
    metermodel: string | null;
    totalcost: number;
    totalprice: string;
    givenergy: string;
    instanceId: string;
}
